# é…ç½®æ–‡ä»¶è¯·ä¸¥æ ¼éµå¾ªyamlè¯­æ³•æ ¼å¼ï¼Œyamlå­¦ä¹ åœ°å€:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

# å®šæ—¶æ—¶é—´
alarm_timed: '8:30'

# æ ¼è¨€æ¸ é“
# 1 : ONEâ—ä¸€ä¸ª
# 2 : è¯éœ¸ï¼ˆæ¯æ—¥è‹±è¯­ï¼ŒåŒè¯­ï¼‰
dictum_channel: 2

friend_infos:
  -
    type: 'group'
    # ç¾¤ç»„å¾®ä¿¡æ˜µç§°
    wechat_name: 'å‘è¿‡ğŸ· å¤´'
    # ç¾¤ç»„åŸå¸‚
    city_name: 'å¹¿å·'
    # è¿è¡Œå¼€å§‹æ—¶é—´
    start_date: '2019-06-14'
    # ç•™è¨€
    sweet_words: ''

  -
    type: 'group'
    wechat_name: 'ğŸ‘ğŸ”ğŸ¶ğŸ â¤ï¸ğŸ”†'
    city_name: 'æ±•å¤´'
    start_date: '2019-06-14'
    sweet_words: ''

  -
    type: 'group'
    wechat_name: '21+1çš„å¤©ç©º(4ä¿1)'
    city_name: 'å¹¿å·'
    start_date: '2019-06-14'
    sweet_words: ''